# Generated by Django 3.2.9 on 2021-11-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211127_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person_images/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('kochi', models.ManyToManyField(blank=True, related_name='kochi', to='posts.Person')),
                ('link_team', models.ManyToManyField(blank=True, related_name='linkteam', to='posts.Person')),
                ('malabar', models.ManyToManyField(blank=True, related_name='malabar', to='posts.Person')),
                ('sac_vsac', models.ManyToManyField(blank=True, related_name='sacvsac', to='posts.Person')),
                ('society_sr', models.ManyToManyField(blank=True, related_name='society_sr', to='posts.Person')),
                ('travancore', models.ManyToManyField(blank=True, related_name='travancore', to='posts.Person')),
            ],
        ),
    ]
