# Generated by Django 3.2.9 on 2021-11-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211127_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tags',
            name='display_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
